RANGER-2831: presto-server-333 start failed due to NoClassDefFoundError
(cherry picked from commit 813b67197ae6e58c21a9e72c7f034779c3efed79)

# Conflicts:
#	distro/src/main/assembly/plugin-presto.xml
#	security-admin/src/main/java/org/apache/ranger/patch/PatchForPrestoToSupportPresto333_J10037.java